build:
    environment:
        php:
            version: 5.6.0
checks:
    php: true
filter:
    excluded_paths:
        - tests/*
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"