<?php

namespace FullRent\Core\Company\Projection;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
}
